### ISSUE TITLE
Program won't run

### ISSUE THREAD

**Issue by mechtech** [notpod/Notpod-1.x#2]
notpod installs just fine on my pc. then when i go to open it states that a .net framework v4.0.30319 is not found and is needed to open notpod. any idea how i get it or is my pc not compatible with notpod?

**Comment by jaranflaath** [comment]
Normally you can install the latest version of .Net Framework from Windows Update. Should it not give you that option, you can try to download from Microsoft here: http://www.microsoft.com/download/en/details.aspx?id=17851

**Comment by jaranflaath** [comment]
Closing issue due to age.
